### PR TITLE
add Dgraph's authentication token

### PR DESCRIPTION
**Pull request by MichelDiz**
Add support for Dgraph's authentication token.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph-js-http/29)

### CODE REVIEW

**Comment by paulftw** [comment]
Hey @MichelDiz please take a look at https://github.com/dgraph-io/dgraph-js-http/commit/cf306a50a790caaf29de14a8cd1a8e88236dda77

I've merged it yesterday as part of adding support for Slash. 
I think it allows adding auth tokens to `/alter` via options.
And also does a couple more things differently: allows users to specify arbitrary headers, allows adding headers to `/query` and `/mutate` as well as `/alter` (that matters for Slash).

In Ratel I do 
```
    const stub = new dgraph.DgraphClientStub(
        url,
        {
            jsonParser: JSONbigint.parse.bind(JSONbigint),
        },
        {
            headers: {
                "X-Auth-Token": "wrK9gCu1fyARDnaZuxR/zvdewK8oiphXpMb6mTxfaW0=",
            },
        },
    );
```
and then all calls have token inserted.

That one doesn't have documentation though. and could benefit from an explicit setter -- `stub.setAuthToken()` or something

**Comment by MichelDiz** [comment]
@danielmai  can you confirm if this PR and the commit from Paul is the same thing?

**Comment by paulftw** [comment]
Closing this one for now, since there are other ways to add custom headers to a stub

**Comment by MichelDiz** [comment]
@paulftw  and what are they? there are docs about it? If I had found anything I wouldn't even start this PR.

**Pull request closed without merging**
