### PR TITLE
Removed redundant health() function

### PR DESCRIPTION
**Pull request by Aelbannan**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph-js-http/22)

### CODE REVIEW

**Review by paulftw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph-js-http/22)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @Aelbannan and @paulftw)

___
*[src/clientStub.ts, line 44 at r1](https://reviewable.io/reviews/dgraph-io/dgraph-js-http/22#-M0SfiQ8-IUpiFmP_FOX:-M0SfiQ9Dor6x2JoViSX:b-5qyscy) ([raw file](https://github.com/dgraph-io/dgraph-js-http/blob/76a0e09e469a93f9fdf12bd9ebc341b633afc763/src/clientStub.ts#L44)):*
Does this actually work for you?
On my machine `getHealth()` throws an error with a legacy server:

```
𝝺 curl localhost:8080/health
OK

𝝺 node
> const dgraph = require('dgraph-js-http')
> const stub = new dgraph.DgraphClientStub('http://localhost:8080')
> stub.callAPI('health')
Promise { <pending> }
> (node:84783) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at http://localhost:8080/health reason: Unexpected token O in JSON at position 0
    at /Users/paul/Projects/Dgraph/Repos/dgraph-js-http/node_modules/node-fetch/lib/body.js:48:31
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:84783) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:84783) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It thus seems like with an old server this function will always throw an error, defeating the purpose.

**Comment by Aelbannan** [comment]
First of all, make sure to use: https://github.com/dgraph-io/ratel/pull/167

So I've tried with 1.0.8 and 1.0.12, both throw 503 errors both with and without this PR. So the behaviour has not changed.

**Comment by Aelbannan** [comment]
I've fixed it. It's a bit hacky though, interested in any feedback.

**Review by paulftw — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph-js-http/22)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @Aelbannan and @paulftw)

___
*[src/clientStub.ts, line 50 at r2](https://reviewable.io/reviews/dgraph-io/dgraph-js-http/22#-M0x80a0ATzBDRNu1a9o:-M0x80a1BTNHEzKI5GjF:b-yftjhb) ([raw file](https://github.com/dgraph-io/dgraph-js-http/blob/858b0d1e6f45fb63584537858dc74c032156b84a/src/clientStub.ts#L50)):*
> ```XML
>         // Check if the the response is OK, but not JSON. If it is, enable the legacy api
>         if (err.name === "FetchError") {
>           if (err.response.status === 200) {
> ```

I'd probably do a raw text fetch just for this case and then parse it, but this is good enough since the pre 1.1 servers won't stay around for long anyway

**Review by paulftw — COMMENTED** [review]
In the future please reply to the code comments using the per comment reply box -- I missed this change by only checking that field

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph-js-http/22#-:-M0x8Pd-3k8rm3sRjIxj:b-5rydxv)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @Aelbannan and @paulftw)

**Review by Aelbannan — COMMENTED** [review]
Sure, will do 

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph-js-http/22#-:-M0xQYamDpYQb9sVf3M9:bt1x36d)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @Aelbannan)

**Pull request merged**
